import type { Hazard, Language } from '../core/types';

/**
 * Fixed, reviewed phrases. The model only picks a hazard category; these are the only action-related words the user
 * ever hears. Policy (decided with the user, 2026-10-04): advisory wording ("may", "might"), a short "pause and look"
 * at most; never "run", never a route, never the word "safe", and say so when unsure.
 * Every phrase must pass `isCommandLike` as false (enforced by a test).
 *
 * Scene "friendly hints" (beach, road, nature) and "no obvious danger" reassurances were removed on 2026-10-04: live
 * testing showed the scene label was wrong about half the time and hazard detection never fired on 12 public images,
 * so such lines would have been confident-sounding noise.
 */
export type ActionableHazard = Exclude<Hazard, 'none' | 'unclear'>;

interface PhraseSet {
  hazard: Record<ActionableHazard, string>;
  unclear: string;
  withheld: string;
  disclaimer: string;
}

export const PHRASES: Record<Language, PhraseSet> = {
  zh: {
    hazard: {
      vehicle: '前方可能有车辆,建议先停下来观察周围。',
      water_edge: '附近可能有水边,脚下可能湿滑,建议放慢并留意脚下。',
      height_drop: '附近可能有台阶或落差,建议先停下来确认脚下。',
      crowd: '周围可能人比较多,建议留意身边的人。',
      animal: '附近可能有动物,建议与它保持一点距离。',
      fire_smoke: '画面里可能有火或烟,建议先停下来确认情况,并与它保持距离。',
      obstacle: '前方可能有障碍物,建议放慢并留意。',
    },
    unclear: '画面或光线不足,我无法判断周围的情况。',
    withheld: '这段描述含有指令或安全判断的措辞,已被拦截,没有朗读。',
    disclaimer:
      '以上内容由人工智能根据当前画面自动生成,仅供参考。危险提示是实验性的,可能漏报,没有提示不代表没有危险。它不能代替现场判断、专业培训或辅助工具与人员的帮助。',
  },
  en: {
    hazard: {
      vehicle: 'A vehicle may be nearby. It may be wise to pause and look around.',
      water_edge: 'There may be water nearby and the ground may be slippery. Slowing down and watching your footing may help.',
      height_drop: 'There may be steps or a drop nearby. Pausing to check your footing may help.',
      crowd: 'It may be crowded here. Keeping an eye on the people around you may help.',
      animal: 'An animal may be nearby. Keeping a little distance may help.',
      fire_smoke: 'There may be fire or smoke in view. Pausing to check, and staying at a distance, may be wise.',
      obstacle: 'There may be an obstacle ahead. Slowing down and watching may help.',
    },
    unclear: 'The image or lighting is not good enough for me to judge the surroundings.',
    withheld: 'This description contained command-like or safety-judgment wording and was withheld, not read aloud.',
    disclaimer:
      'This is automatically generated by AI from the current image, for reference only. Hazard alerts are experimental and can be missed; no alert does not mean there is no danger. It cannot replace on-site judgment, professional training, or help from assistive tools and people.',
  },
};
