import type { Hazard, Language, Scene } from '../core/types';

/**
 * Fixed, reviewed phrases. The model only picks a category; these are the only action-related words the
 * user ever hears. Policy (decided with the user, 2026-10-04): advisory wording ("may", "might"), a short
 * "pause and look" at most; never "run", never a route, never the word "safe", and say so when unsure.
 * Every phrase must pass `isCommandLike` as false (enforced by a test).
 */
export type ActionableHazard = Exclude<Hazard, 'none' | 'unclear'>;

interface PhraseSet {
  hazard: Record<ActionableHazard, string>;
  scene: Partial<Record<Scene, string>>;
  unclear: string;
  uncertainHazard: string;
  withheld: string;
  noHazardNote: string;
  disclaimer: string;
}

export const PHRASES: Record<Language, PhraseSet> = {
  zh: {
    hazard: {
      vehicle: '前方可能有车辆,建议先停下来观察周围。',
      water_edge: '附近可能有水边,脚下可能湿滑,建议放慢并留意脚下。',
      height_drop: '附近可能有台阶或落差,建议先停下来确认脚下。',
      crowd: '周围可能人比较多,建议留意身边的人。',
      animal: '附近可能有动物,建议与它保持一点距离。',
      fire_smoke: '画面里可能有火或烟,建议先停下来确认情况,并与它保持距离。',
      obstacle: '前方可能有障碍物,建议放慢并留意。',
    },
    scene: {
      road: '这里看起来像道路环境,过马路前建议先停下,看一看、听一听。',
      beach: '这里看起来像海滩,是放松的好地方,也请留意水边和脚下。',
      nature: '这里看起来是自然环境,可以放松享受一下。',
    },
    unclear: '画面或光线不足,我无法判断周围的情况。',
    uncertainHazard: '画面里可能有需要留意的情况,但我不太确定,建议你自己确认周围。',
    withheld: '这段描述含有指令式的措辞,已被拦截,没有朗读。',
    noHazardNote: '这一帧里没有看到明显的危险迹象,但这不代表安全,也不能代替你自己的判断。',
    disclaimer: '以上内容由人工智能根据当前画面自动生成,仅供参考,不能代替现场判断、专业培训或辅助工具与人员的帮助。',
  },
  en: {
    hazard: {
      vehicle: 'A vehicle may be nearby. It may be wise to pause and look around.',
      water_edge: 'There may be water nearby and the ground may be slippery. Slowing down and watching your footing may help.',
      height_drop: 'There may be steps or a drop nearby. Pausing to check your footing may help.',
      crowd: 'It may be crowded here. Keeping an eye on the people around you may help.',
      animal: 'An animal may be nearby. Keeping a little distance may help.',
      fire_smoke: 'There may be fire or smoke in view. Pausing to check, and staying at a distance, may be wise.',
      obstacle: 'There may be an obstacle ahead. Slowing down and watching may help.',
    },
    scene: {
      road: 'This looks like a road environment. Before crossing, it may help to pause and look and listen.',
      beach: 'This looks like a beach, a nice place to relax. It may help to stay aware of the water and your footing.',
      nature: 'This looks like a natural setting, a good place to enjoy.',
    },
    unclear: 'The image or lighting is not good enough for me to judge the surroundings.',
    uncertainHazard: 'There may be something worth watching in view, but I am not sure. It may be best to check your surroundings yourself.',
    withheld: 'This description contained command-like wording and was withheld, not read aloud.',
    noHazardNote: 'I do not see obvious signs of danger in this frame, but that does not mean it is safe, and it cannot replace your own judgment.',
    disclaimer: 'This is automatically generated by AI from the current image. It is for reference only and cannot replace on-site judgment, professional training, or help from assistive tools and people.',
  },
};
