import type { Language, ProviderErrorKind } from '../core/types';

export interface Strings {
  title: string;
  holdToTalk: string;
  releaseToSend: string;
  analyze: string;
  zoomIn: string;
  zoomOut: string;
  zoomReset: string;
  repeat: string;
  stop: string;
  settings: string;
  back: string;
  modeLocal: string;
  modeRemote: string;
  thinking: string;
  capturing: string;
  listening: string;
  heard: string;
  notUnderstood: string;
  elapsed: (seconds: number) => string;
  zoomLabel: (percent: number) => string;
  cameraDenied: string;
  micDenied: string;
  speechUnavailable: string;
  remoteWarning: string;
  remoteConsentTitle: string;
  remoteConsentBody: string;
  agree: string;
  cancel: string;
  errors: Record<ProviderErrorKind | 'camera' | 'unknown', string>;
  disclaimerShort: string;
}

export const STRINGS: Record<Language, Strings> = {
  zh: {
    title: '视觉助手',
    holdToTalk: '按住说话',
    releaseToSend: '松开发送',
    analyze: '看看周围',
    zoomIn: '放大',
    zoomOut: '缩小',
    zoomReset: '还原',
    repeat: '重复',
    stop: '停止朗读',
    settings: '设置',
    back: '返回',
    modeLocal: '本机 AI',
    modeRemote: '远程服务器',
    thinking: '正在看…',
    capturing: '正在拍照…',
    listening: '正在听…',
    heard: '听到',
    notUnderstood: '没听懂,可以说:看看周围、放大、缩小、还原、重复、停止。',
    elapsed: (s) => `耗时 ${s.toFixed(1)} 秒`,
    zoomLabel: (p) => `变焦 ${p}%`,
    cameraDenied: '没有相机权限,请在系统设置中允许使用相机。',
    micDenied: '没有麦克风或语音识别权限,请在系统设置中允许。',
    speechUnavailable: '此设备或此版本暂不支持语音识别,请用按钮操作。',
    remoteWarning: '远程模式:画面会发送到你设置的服务器。',
    remoteConsentTitle: '使用远程服务器?',
    remoteConsentBody: '拍到的画面会通过网络发送到你设置的服务器进行分析。只在你信任该服务器时使用。',
    agree: '同意',
    cancel: '取消',
    errors: {
      network: '连不上服务器,请检查网络和服务器地址。',
      timeout: '服务器响应太慢,请稍后再试。',
      auth: '服务器拒绝了访问密钥,请检查设置。',
      server: '服务器出错了,请稍后再试。',
      invalid_output: '这次没有得到可靠的结果,我不会猜测。请再试一次。',
      not_ready: '本机 AI 还没准备好,请先在设置里下载模型。',
      cancelled: '已取消。',
      camera: '拍照失败,请检查相机。',
      unknown: '出了点问题,请再试一次。',
    },
    disclaimerShort: '由人工智能自动生成,仅供参考,不能代替你自己的判断。',
  },
  en: {
    title: 'Vision Helper',
    holdToTalk: 'Hold to talk',
    releaseToSend: 'Release to send',
    analyze: 'Look around',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    zoomReset: 'Reset',
    repeat: 'Repeat',
    stop: 'Stop speaking',
    settings: 'Settings',
    back: 'Back',
    modeLocal: 'On-device AI',
    modeRemote: 'Remote server',
    thinking: 'Looking…',
    capturing: 'Taking a picture…',
    listening: 'Listening…',
    heard: 'Heard',
    notUnderstood: 'I did not understand. Try: look around, zoom in, zoom out, reset, repeat, stop.',
    elapsed: (s) => `${s.toFixed(1)} s`,
    zoomLabel: (p) => `Zoom ${p}%`,
    cameraDenied: 'Camera permission is off. Please allow it in system settings.',
    micDenied: 'Microphone or speech recognition permission is off. Please allow it in system settings.',
    speechUnavailable: 'Speech recognition is not available here. Please use the buttons.',
    remoteWarning: 'Remote mode: pictures are sent to the server you configured.',
    remoteConsentTitle: 'Use a remote server?',
    remoteConsentBody: 'Pictures you take are sent over the network to the server you configured. Only use a server you trust.',
    agree: 'Agree',
    cancel: 'Cancel',
    errors: {
      network: 'Cannot reach the server. Check your network and the server address.',
      timeout: 'The server is too slow to answer. Please try again later.',
      auth: 'The server rejected the access key. Please check settings.',
      server: 'The server had a problem. Please try again later.',
      invalid_output: 'I did not get a reliable result this time, and I will not guess. Please try again.',
      not_ready: 'On-device AI is not ready. Please download the model in settings first.',
      cancelled: 'Cancelled.',
      camera: 'Could not take a picture. Please check the camera.',
      unknown: 'Something went wrong. Please try again.',
    },
    disclaimerShort: 'Generated by AI, for reference only; it cannot replace your own judgment.',
  },
};

export function errorMessage(kind: ProviderErrorKind | 'camera' | 'unknown', language: Language): string {
  return STRINGS[language].errors[kind];
}
